SET foreign_key_checks = 0;
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,1,'BANCO DO BRASIL',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,3,'BANCO DA AMAZONIA',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,4,'BANCO DO NORDESTE DO BRASIL',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,12,'BANCO STANDARD DE INVESTIMENTOS',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,21,'BANESTES  BANCO DO ESTADO DO ESPIRITO SANTO',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,24,'BANCO DE PERNAMBUCO -BANDEPE',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,25,'BANCO ALFA',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,27,'BANCO DO ESTADO DE SANTA CATARINA',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,29,'BANCO BANERJ',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,31,'BANCO BEG',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,33,'BANCO SANTANDER',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,34,'BANCO DO ESTADO DO AMAZONAS',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,36,'BANCO BRADESCO BBI',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,37,'BANCO DO ESTADO DO PARA',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,38,'BANCO BANESTADO',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,39,'BANCO DO ESTADO DO PIAUI  - BEP',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,40,'BANCO CARGILL',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,41,'BANCO DO ESTADO DO RIO GRANDE DO SUL',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,44,'BANCO BVA SA',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,45,'BANCO OPPORTUNITY',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,47,'BANCO DO ESTADO DE SERGIPE',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,62,'HIPERCARD BANCO MÚLTIPLO',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,63,'BANCO IBI  - BANCO MULTIPLO',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,64,'GOLDMAN SACHS DO BRASIL BANCO MÚLTIPLO',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,65,'LEMON BANK BANCO MÚLTIPLO S..A',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,66,'BANCO MORGAN STANLEY',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,69,'BPN BRASIL BANCO MÚLTIPLO',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,70,'BRB - BANCO DE BRASILIA',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,72,'BANCO RURAL MAIS',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,73,'BB BANCO POPULAR DO BRASL',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,74,'BANCO J.SAFRA',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,75,'BANCO CR2',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,76,'BANCO KDB DO BRASIL',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,78,'BES INVESTIMENTO DO BRASIL - BANCO DE INVESTIMENTO',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,95,'BANCO CONFIDENCE DE CÂMBIO',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,96,'BANCO BM&F DE SERVIÇOS DE LIQUIDAÇÃO E CUSTÓDIA',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,104,'CAIXA ECONÔMICA FEDERAL',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,107,'BANCO BBM',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,116,'BANCO ÚNICO',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,119,'BANCO WESTERN UNION DO BRASIL',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,125,'BRASIL PLURAL - BANCO MÚLTIPLO',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,151,'BANCO NOSSA CAIXA',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,175,'BANCO FINASA',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,184,'BANCO ITAÚ - BBA',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,204,'BANCO BRADESCO CARTÕES',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,208,'BANCO UBS PACTUAL',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,212,'BANCO MATONE',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,213,'BANCO ARBI',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,214,'BANCO DIBENS',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,215,'BANCO ACOMERCIAL E DE INVESTIMENTO SUDAMERIS',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,217,'BANCO JOHN DEERE',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,218,'BANCO BONSUCESSO',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,222,'BANCO CLAYON BRASIL',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,224,'BANCO FIBRA',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,225,'BANCO BRASCAN',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,229,'BANCO CRUZEIRO DO SUL',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,230,'UNICARD BANCO MÚLTIPLO',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,233,'BANCO GE CAPITAL',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,237,'BANCO BRADESCO',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,241,'BANCO CLASSICO',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,243,'BANCO MAXIMA',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,246,'BANCO ABC-BRASIL',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,248,'BANCO BOAVISTA INTERATLANTICO',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,249,'BANCO INVESTCRED UNIBANCO',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,250,'BANCO SCHAHIN',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,252,'BANCO FININVEST',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,254,'PARANÁ BANCO',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,263,'BANCO CACIQUE',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,265,'BANCO FATOR',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,266,'BANCO CEDULA',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,300,'BANCO DE LA NACION ARGENTINA',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,318,'BANCO BMG',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,320,'BANCO INDUSTRIAL E COMERCIAL',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,341,'BANCO ITAU',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,356,'BANCO ABN AMRO REAL',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,366,'BANCO SOCIETE GENERALE BRASIL',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,370,'BANCO WESTLB DO BRASIL',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,376,'BANCO J.P. MORGAN',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,389,'BANCO MERCANTIL DO BRASIL',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,394,'BANCO BMC',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,399,'HSBC BANK BRASIL -BANCO MULTIPLO',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,409,'UNIBANCO - UNIAO DE BANCOS BRASILEIROS',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,412,'BANCO CAPITAL',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,422,'BANCO SAFRA',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,453,'BANCO RURAL',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,456,'BANCO DE TOKYO-MITSUBISHI UFJ BRASIL',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,464,'BANCO SUMITOMO MITSUI BRASILEIRO',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,473,'BANCO CAIXA GERAL - BRASIL',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,477,'CITIBANK N.A.',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,479,'BANCO ITAUBANK',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,487,'DEUTSCHE BANK S. A. - BANCO ALEMAO',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,488,'JPMORGAN CHASE BANK, NATIONAL ASSOCIATION',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,492,'ING BANK N.V.',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,494,'BANCO DE LA REPUBLICA ORIENTAL DEL URUGUAY',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,495,'BANCO DE LA PROVINCIA DE BUENOS AIRES',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,505,'BANCO CREDIT SUISSE (BRASIL)',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,600,'BANCO LUSO BRASILEIRO',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,604,'BANCO INDUSTRIAL DO BRASIL S. A.',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,610,'BANCO VR',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,611,'BANCO PAULISTA',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,612,'BANCO GUANABARA',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,613,'BANCO PECUNIA',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,623,'BANCO PANAMERICANO',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,626,'BANCO FICSA',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,630,'BANCO INTERCAP',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,633,'BANCO RENDIMENTO',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,634,'BANCO TRIANGULO',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,637,'BANCO SOFISA',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,638,'BANCO PROSPER',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,641,'BANCO ALVORADA',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,643,'BANCO PINE',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,652,'BANCO ITAÚ HOLDING FINANCEIRA',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,653,'BANCO INDUSVAL',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,654,'BANCO A.J. RENNER',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,655,'BANCO VOTORANTIM',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,707,'BANCO DAYCOVAL',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,719,'BANIF - BANCO INTERNACIONAL DO FUNCHAL (BRASIL),',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,721,'BANCO CREDIBEL',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,734,'BANCO GERDAU',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,735,'BANCO POTTENCIAL',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,738,'BANCO MORADA',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,739,'BANCO BGN',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,740,'BANCO BARCLAYS',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,741,'BANCO RIBEIRAO PRETO',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,743,'BANCO SEMEAR',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,744,'BANKBOSTON N.A.',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,745,'BANCO CITIBANK',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,746,'BANCO MODAL',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,747,'BANCO RABOBANK INTERNATIONAL BRASIL',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,748,'BANCO COOPERATIVO SICREDI',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,749,'BANCO SIMPLES',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,751,'DRESDNER BANK BRASIL  BANCO MULTIPLO.',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,752,'BANCO BNP PARIBAS BRASIL',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,753,'BANCO COMERCIAL URUGUAI',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,755,'BANK OF AMERICA MERRILL LYNCH BANCO MÚLTIPLO',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,756,'BANCO COOPERATIVO DO BRASIL  - BANCOOB',now(),now(),0);
REPLACE INTO fin_banco(id,codigo_banco,nome,inserted,updated,version) VALUES(NULL,757,'BANCO KEB DO BRASIL',now(),now(),0);